CREATE SCHEMA auth;

CREATE SCHEMA employee;

CREATE TYPE auth.auth_role AS ENUM ('USER', 'ADMIN', 'LEFT');

CREATE TYPE employee.employee_role AS ENUM ('DEPARTMENT_CHIEF', 'TEAM_CHIEF', 'EMPLOYEE', 'LEFT');

CREATE TABLE auth.account
(
    id            BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name     VARCHAR(255)                NOT NULL,
    password_hash VARCHAR(255)                NOT NULL,
    phone         VARCHAR(15),
    email         VARCHAR(255),
    auth_role     auth.auth_role              NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT ck_user_deleted_state CHECK ((
        (auth.account.auth_role <> 'LEFT' AND auth.account.deleted_at IS NULL)
            OR
        (auth.account.auth_role = 'LEFT' AND auth.account.deleted_at IS NOT NULL)
        ))
);
CREATE UNIQUE INDEX uq_user_name
    ON auth.account (user_name) WHERE auth.account.auth_role <> 'LEFT';
CREATE INDEX ix_active_user_created_at
    ON auth.account (created_at DESC NULLS LAST) WHERE auth.account.auth_role <> 'LEFT';
CREATE INDEX ix_delete_user_deleted_at
    ON auth.account (deleted_at DESC NULLS LAST) WHERE auth.account.auth_role = 'LEFT';

CREATE TABLE auth.refresh_token
(
    id         BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT                      NOT NULL,
    token      VARCHAR(255)                NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT uq_active_refresh_token UNIQUE (token),
    CONSTRAINT fk_refresh_token_user_1
        FOREIGN KEY (account_id)
            REFERENCES auth.account (id)
            ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX ix_refresh_token_user ON auth.refresh_token (account_id);
CREATE INDEX ix_refresh_token_expire ON auth.refresh_token (expires_at);

CREATE TABLE employee.position
(
    id               BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    position_code    VARCHAR(255) NOT NULL,
    position_name    VARCHAR(255) NOT NULL,
    basic_salary     BIGINT       NOT NULL,
    incentive_salary BIGINT       NOT NULL,
    CONSTRAINT pk_position PRIMARY KEY (id),
    CONSTRAINT uq_position_code UNIQUE (position_code),
    CONSTRAINT uq_position_position_name UNIQUE (position_name)
);

CREATE TABLE employee.department
(
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_code VARCHAR(255) NOT NULL,
    department_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT uq_department_code UNIQUE (department_code),
    CONSTRAINT uq_department_department_name UNIQUE (department_name)
);

CREATE TABLE employee.team
(
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    team_code     VARCHAR(255) NOT NULL,
    department_id BIGINT       NOT NULL,
    team_name     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_team PRIMARY KEY (id),
    CONSTRAINT uq_team_code UNIQUE (team_code),
    CONSTRAINT uq_team_team_name UNIQUE (team_name),
    CONSTRAINT fk_team_department_1
        FOREIGN KEY (department_id)
            REFERENCES employee.department (id)
            ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX ix_team_department ON employee.team (department_id);

CREATE TABLE employee.profile
(
    id            BIGINT                      NOT NULL,
    employee_code varchar(255)                NOT NULL,
    employee_name varchar(255)                NOT NULL,
    team_id       BIGINT                      NOT NULL,
    employee_role employee.employee_role      NOT NULL,
    position_id   BIGINT                      NOT NULL,
    created_by    BIGINT                      NOT NULL,
    updated_by    BIGINT                      NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_profile PRIMARY KEY (id),
    CONSTRAINT uq_employee_code UNIQUE (employee_code),
    CONSTRAINT ck_employee_left_state CHECK ((
        (employee.profile.employee_role <> 'LEFT' AND employee.profile.deleted_at IS NULL)
            OR
        (employee.profile.employee_role = 'LEFT' AND employee.profile.deleted_at IS NOT NULL)
        )),
    CONSTRAINT fk_profile_account_1
        FOREIGN KEY (id)
            REFERENCES auth.account (id)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_profile_team_1
        FOREIGN KEY (team_id)
            REFERENCES employee.team (id)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_position_1
        FOREIGN KEY (position_id)
            REFERENCES employee.position (id)
            ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX ix_profile_team ON employee.profile (team_id);
CREATE INDEX ix_position ON employee.profile (position_id);
CREATE INDEX ix_created_by ON employee.profile (created_by);
CREATE INDEX ix_updated_by ON employee.profile (updated_by);
CREATE INDEX ix_active_employee_created_at
    ON employee.profile (created_at DESC NULLS LAST) WHERE employee.profile.employee_role <> 'LEFT';
CREATE INDEX ix_left_employee_deleted_at
    ON employee.profile (deleted_at DESC NULLS LAST) WHERE employee.profile.employee_role = 'LEFT';

CREATE SEQUENCE employee.employee_code_seq INCREMENT BY 1;