CREATE TYPE employee.attendance_status AS ENUM (
    'PRESENT',
    'LATE',
    'ABSENT',
    'ANNUAL_LEAVE',
    'HALF_DAY_AM',
    'HALF_DAY_PM'
    );

CREATE TABLE employee.attendance
(
    id                BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id       BIGINT                      NOT NULL,
    commute_date      DATE                        NOT NULL,
    commute_time      TIMESTAMP(6) WITH TIME ZONE NULL,
    quit_time         TIMESTAMP(6) WITH TIME ZONE NULL,
    attendance_status employee.attendance_status  NOT NULL,
    remark            TEXT                        NULL,
    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_attendance_profile_1
        FOREIGN KEY (employee_id)
            REFERENCES employee.profile (id)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_employee_commute_date UNIQUE (employee_id, commute_date),
    CONSTRAINT ck_attendance_time CHECK (commute_time IS NULL OR quit_time IS NULL OR commute_time <= quit_time)
);

CREATE TABLE employee.salary
(
    id               BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id      BIGINT  NOT NULL,
    start_date       DATE    NOT NULL,
    end_date         DATE    NOT NULL,
    commute_days     INTEGER NOT NULL,
    late_days        INTEGER NOT NULL,
    absent_days      INTEGER NOT NULL,
    basic_salary     BIGINT  NOT NULL,
    incentive_salary BIGINT  NOT NULL,
    bonus_salary     BIGINT  NOT NULL,
    remark           TEXT    NULL,
    CONSTRAINT pk_salary PRIMARY KEY (id),
    CONSTRAINT fk_salary_profile_1
        FOREIGN KEY (employee_id)
            REFERENCES employee.profile (id)
            ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_employee_date UNIQUE (employee_id, start_date, end_date),
    CONSTRAINT ck_salary_date CHECK ( start_date <= end_date )
);