name: Deploy Dev Only CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Create .env
        run: |
          cat <<EOF > .env
          DB_URL=${{ secrets.DEV_DB_URL }}
          DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
          JWT_ACCESS_SECRET=${{ secrets.DEV_JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.DEV_JWT_REFRESH_SECRET }}
          API_KEY=${{ secrets.DEV_API_KEY }}
          EOF

      - name: Build
        run: ./gradlew bootJar

      - name: Upload bootJar
        uses: actions/upload-artifact@v4
        with:
          name: izen
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 7