name: Deploy Dev Only CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Test & Build
    runs-on: ubuntu-latest
    environment: development

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: izen_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d izen_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Integration Test And Build
        run: ./gradlew clean build

      - name: Prepare Artifact
        run: |
          mkdir -p artifact/report

          cp build/libs/izen-1.0.0.jar artifact/app.jar
          cp -r build/reports/tests/test/* artifact/report/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: izen-dev
          path: artifact/
          if-no-files-found: error
          retention-days: 7